# Generated by Django 6.0.2 on 2026-02-25 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='expected_return_date',
            field=models.DateField(default=datetime.date(2026, 2, 25)),
            preserve_default=False,
        ),
    ]
